FROM python:3.11-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app
RUN chmod +x /app/scripts/wait_for_db.sh

CMD ["bash","-lc","/app/scripts/wait_for_db.sh && uvicorn services.api_service.main:app --host 0.0.0.0 --port 8080"]
